<?php
/**
* Trait ProductTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait ProductTrait
{
    
    public function getCasts()
    {
        $casts = parent::getCasts();
                                                        $casts['created_at'] = 'datetime';
                                                $casts['updated_at'] = 'datetime';
                                        
        return $casts;
    }

    public function getTable()
    {
        return $this->table ?? 'products';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'name',
                    ];
    }

    }
