<?php
/**
* Trait WheelTrait
*
* Generated by LaraGen, Do not modify it manually.
*/

namespace App\Models\GeneratedTraits;

trait WheelTrait
{
    
    public function getCasts()
    {
        $casts = parent::getCasts();
                                                        $casts['created_at'] = 'datetime';
                                                $casts['updated_at'] = 'datetime';
                                                            
        return $casts;
    }

    public function getTable()
    {
        return $this->table ?? 'wheels';
    }

    public function getFillable()
    {
        if (!empty($this->fillable)) {
            return $this->fillable;
        }

        return [
                            'id',
                            'created_at',
                            'updated_at',
                            'year',
                            'wheel_id',
                    ];
    }

                        public function wheel(): \Illuminate\Database\Eloquent\Relations\BelongsTo
            {
                return $this->belongsTo(\App\Models\Car::class);
            }
                            }
